### ISSUE TITLE
aoc-cli 0.5

### ISSUE THREAD

**Issue by tguichaoua** [fspoettel/advent-of-code-rust#11]
`aoc-cli` [release `v0.5.0` 4 days ago](https://github.com/scarvalhojr/aoc-cli/releases/tag/0.5.0) and rename the `--file` command flag by `--input-file`.

It can be solved by either : 
- install `aoc-cli` v0.4 with `cargo install aoc-cli --version 0.4`
- patch `src/bin/download.rs` with
https://github.com/fspoettel/advent-of-code-rust/blob/a6405f2edb7b626696dc72da7e81176c304536c0/src/bin/download.rs#L66-L72
```diff
    cmd_args.append(&mut vec![
-      "--file".into(),
+      "--input-file".into(),
        tmp_file_path.to_string_lossy().to_string(),
        "--day".into(),
        args.day.to_string(),
        "download".into(),
    ]);
```

**Comment by fspoettel** [comment]
Ugh, second update in a row that broke. I implemented both of your suggestions - updated to v0.5.0 and pinned in the readme command. Thanks!
