### ISSUE TITLE
bug: the main binary shadow aoc-cli

### ISSUE THREAD

**Issue by tguichaoua** [fspoettel/advent-of-code-rust#12]
The `download` script run `aoc` 

https://github.com/fspoettel/advent-of-code-rust/blob/9bc635a056d11741e28fdc388aa2871b48465237/src/bin/download.rs#L76

But because the package's name is also `aoc`, when it is built it generates a `aoc.exe` that shadows `aoc-cli`.

**Comment by fspoettel** [comment]
@tguichaoua thank you for all your contributions today, I appreciate it! 🙃 

I guess we could go for something like `aoc-template` to disambiguate. I'll add a commit and bump the template version.

**Comment by fspoettel** [comment]
@tguichaoua I renamed the package to `advent_of_code` which should solve this.

The best way to update your repo (that I know of) is to apply the changes as a patch:

```sh
# in this repo
git diff v0.7.0 v0.8.0 > package_rename.diff
# apply to your repo
git apply <path_to_diff>
```
if there are incompatible edits to the readme or any other file, you might have to remove that diff block from the patch.
