### ISSUE TITLE
Cargo configuration doesn't find the target

### ISSUE THREAD

**Issue by AlessandroGrassi99** [fspoettel/advent-of-code-rust#14]
Hello! I was trying to solve the first exercise with your template, but if I run `cargo build` or `cargo scaffold 01`, the output is always the same:
```
error: failed to parse manifest at `/home/herz/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```

Thank you :)

**Comment by fspoettel** [comment]
@AlessandroGrassi99 It looks like there's a `cargo.toml` file in your home directory. Can you try removing it? If I recall correctly, the topmost `cargo` file takes precedence which would lead to this error.

**Comment by AlessandroGrassi99** [comment]
Forgive me for bothering you, you are right. I didn't know about this behavior from Cargo. But I still don't understand why your repo didn't build, but the others did.

**Comment by fspoettel** [comment]
no problem, happy advent of code! 🎄
