### ISSUE TITLE
RFC: Separate parsing from solutions?

### ISSUE THREAD

**Issue by fspoettel** [fspoettel/advent-of-code-rust#15]
[Implementation](https://github.com/fspoettel/advent-of-code-2022/blob/main/src/bin/scaffold.rs)

Currently experimenting with a separately timed parser util on my solution repo, might add to template after this year concludes.

Advantages:
- parser code is not timed twice.
- parsing set up in template.
- can use macro to generate `main()`.

Disadvantages:
- input has to be `Clone`.
-  replacing the macro (if needed for some reason) might not be clear for rust beginners (which this is aimed at).

```rs
type Input<'a> = Vec<&'a str>;

fn parse(input: &str) -> Input {
    input.lines().collect()
}

pub fn part_one(input: Input) -> Option<u32> {
    None
}

pub fn part_two(input: Input) -> Option<u32> {
    None
}

advent_of_code::main!(4);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_part_one() {
        let input = advent_of_code::read_file("examples", 4);
        assert_eq!(part_one(parse(&input)), None);
    }

    #[test]
    fn test_part_two() {
        let input = advent_of_code::read_file("examples", 4);
        assert_eq!(part_two(parse(&input)), None);
    }
}
```

Example output:
```
🎄 Parser 🎄
(elapsed: 24.96µs)
🎄 Part 1 🎄
13005 (elapsed: 6.00ns)
🎄 Part 2 🎄
11373 (elapsed: 831.00ns)
```

**Comment by aranasaurus** [comment]
I like this idea. I think the disadvantage you listed might be able to be addressed, at least partially by adding something to the README. Step by step example how to change it for one, and then possibly a link to some documentation about the syntax and how it works?

**Comment by Blightwidow** [comment]
I see this was not implemented in the end ? There are already quite a few problems this year that could take advantage of such a notation. Any plan to bring it back?
