### ISSUE TITLE
Allow `solve` to automatically submit inputs

### ISSUE THREAD

**Issue by fspoettel** [fspoettel/advent-of-code-rust#19]
[aoc-cli](https://github.com/scarvalhojr/aoc-cli) supports submitting inputs with a command. It would valuable to support automatic submissions for `solve` behind a flag, e.g. `cargo solve 04 --submit`.

**Comment by fspoettel** [comment]
#21 added a wrapper module for aoc_cli, this should be a bit easier now.

**Comment by fspoettel** [comment]
I implemented this on my 2022 repo [here](https://github.com/fspoettel/advent-of-code-2022/commit/a9a2078acdaf2b71022c5a1300917abccc620e1d). I'll test it tomorrow and if all goes well, write the docs and merge into this template.

The syntax for submissions will be `cargo solve <day> --submit <part>`. `--submit` will be ignored until the part function produces a `Some()` istd. of a `None`.

The implemented solution has two nice side effects:
 1. It uses `.cargo/config.toml`'s `[env]` to set the year, thereby eliminating the `--year` flags.
 2. `solve` is now a command istd. of an alias and accepts `6` in addition to `06` for day input.

**Comment by kwiat1990** [comment]
Hey, I wonder what’s the current state of this pull request?

**Comment by fspoettel** [comment]
@kwiat1990 I am a bit preoccupied with work until march/april. Planning to merge this alongside other improvements (better benchmarks, improved scaffolding) as soon as I have some spare time.
