### ISSUE TITLE
Feature Request: cargo scaffold + cargo download

### ISSUE THREAD

**Issue by alexfertel** [fspoettel/advent-of-code-rust#42]
Thank you for creating this template!

I have a very small request for a nice-to-have feature. After setting up my local copy of the template, l find myself running `cargo scaffold <day>` and, right after, I am running `cargo download <day>.`. I think a new flag to `cargo scaffold` like `--download` or even a separate command like `cargo generate <day>` that combines both steps would be nice.

What do you think?

**Comment by fspoettel** [comment]
I think this is a good idea and would accept a PR for this.

The `scaffold --download` flag seems like a good way to go about it and is less work to document than a separate command.
