### ISSUE TITLE
Time individual puzzles

### ISSUE THREAD

**Issue by MLNW** [fspoettel/advent-of-code-rust#45]
In the light of solutions that may take a long time to run it would be great to have the option to time only one puzzle.
I.e.: allow `cargo time 5` to only time day 5.

I guess the hardest bit would be to include the result in the benchmark table. Though it should be manageable.

**Comment by fspoettel** [comment]
I expected this issue after today 😆. I would accept a PR for this. An `--only-missing` flag could also be a valid approach.

 I think the complexity lies in updating the benchmark table when days or parts need to be spliced in etc.

---

In the meantime, maybe adjusting the benchmark count for abnormally long cases could solve the immediate pain. It is defined here:

https://github.com/fspoettel/advent-of-code-rust/blob/47e4f227bdb3efe5981e3b35621eba4188d3352f/src/template/runner.rs#L54-L60

**Comment by fspoettel** [comment]
you can also check out the changes in #44 we just merged. this would allow you to skip running offending slow parts for a solution temporarily.

**Comment by MLNW** [comment]
Sounds like a simple solution to meOn Dec 7, 2023 10:29, Tristan Guichaoua ***@***.***> wrote:

I think the complexity lies in updating the benchmark table when days or parts need to be spliced in etc.

The benchmark table can be cached in a json file, so that it make it easier to update a specific day or part and then update the table in the README

**Comment by fspoettel** [comment]
> The benchmark table can be cached in a json file, so that it make it easier to update a specific day or part and then update the table in the README

Good idea! 💪 That sounds like a reasonable implementation.

**Comment by tguichaoua** [comment]
I prefer option A, it's more likely that the user wants to update the time for new solutions rather than recalculating everything.
Also it would be interesting to have `cargo time <day>` to update a specific day.

**Comment by fspoettel** [comment]
Thanks! And I agree about `day`, that option seems useful going back and optimizing (which I still need to do for day 5...)

**Comment by MLNW** [comment]
I agree, only run time for missing days and provide the option to run time for a specific day. Thanks for taking the time!
