### ISSUE TITLE
File for helper functions

### ISSUE THREAD

**Issue by xsebek** [fspoettel/advent-of-code-rust#60]
Hi, I am a beginner in rust and I have problems extracting common helper functions to a file.

For example let's say that I wanted to factor out a common [`transpose`](https://github.com/xsebek/aoc-rust/blob/0c5dc037d0678ed66dbe63e16358e025be82f45e/src/bin/07.rs#L165-L172) function that I repeatedly used in days 7, 11 and 13. With the template it seems I can't do that in the `bin` folder, right? 😕 

If possible, it would be really nice if there was an empty file in the template already for this purpose.

**Comment by fspoettel** [comment]
The `./lib.rs` file is the correct place for adding helper functions as by rust conventions. You can then import them in your solutions, as long as you declare them `pub`.

You can also register further modules there. As an example, you can check out what this looks like in [my repo for this year](https://github.com/fspoettel/advent-of-code-2023/blob/main/src/lib.rs).

**Comment by fspoettel** [comment]
Let me know if you run into further issues with this, closing for now.
